### ISSUE TITLE
General documentation

### ISSUE THREAD

**Issue by BuonOmo** [rgeo/rgeo#235]
We should add more documentation.

## ROADMAP

- [ ] examples
  - [ ] an example on a polygon containing a point
  - [ ] examples from [rgeo-geojson issues](https://github.com/rgeo/rgeo-geojson/issues?q=is%3Aissue+sort%3Aupdated-desc+label%3Adocumentation+)
  - [ ] more examples (**help wanted**)
- [ ] parse wkt/wkb/geojson/shapefile/...
- [x] which factory should I use ?
- [x] move https://github.com/rgeo/rgeo/blob/master/Spatial_Programming_With_RGeo.md to the wiki
- [x] add compatibility per factory table
- [x] ~update the wiki home~ update the readme with links to docs
- [x] update the README.md with a link to the wiki (link to doc section, see #243)
- [x] update github pages (see https://rgeo.info)

**Comment by tstewart-writer** [comment]
I moved the "An Introduction to Spatial Programming With RGeo" article to the wiki, should I remove the original markdown file?

I'd like to contribute to the documentation, but I'm not really sure where docs should go. Published on the wiki? Or [Github pages](https://github.com/rgeo/rgeo.github.io), since I notice an update is also on the list of tasks. I'm more partial to the later option, since it allows a more docs as code approach. I've seen very few up-to-date wikis on Github.

**Comment by keithdoggett** [comment]
@tstewart-writer thanks for your interest! I think we can remove the original file since it's in the wiki.

From my perspective, I find it easier to write in the wiki, but I agree that they're rarely up to date and not viewed often. My ideal usage for the wiki would be to link every page on the README after a brief introduction to the topic and a short example. This is an example of what I'm thinking: https://github.com/rgeo/rgeo-activerecord/blob/v7-dev/README.md#spatial-factories-for-columns although the link to the wiki should probably go under the header to be more prominent.

I'm not opposed to adding docs on the website though. Do you have any examples of how you're thinking it would be formatted?

**Comment by BuonOmo** [comment]
@tstewart-writer @keithdoggett I think writing in the wiki first is the way to go. In a few month we should have all the doc we need, and we'll be able to update the github page as well ! As of an example of a useful and well maintained wiki, you can check [mperham's Sidekiq](https://github.com/mperham/sidekiq/wiki).

Another point for updating github pages afterward is that we'll know better what we need that doesn't fit in markdown format. Nowadays, the only topic that cannot fit easily is the listing of features per factory that @keithdoggett wanted to do. However, there may be more that we have not thought of.

**Comment by tstewart-writer** [comment]
@BuonOmo @keithdoggett I haven't sat down to create a design proposal or anything, but I was just thinking along the lines of [Ruby Object Mapper](https://rom-rb.org/), where they have sections with guides/tutorials for each of their projects in addition to their YARD generated reference docs.

The main problem I see with wikis is that the content is often separate from the project, even though they are part of the same Github repository. People add pages, they never get updated and are out of date. Sometimes there are multiple pages with contradictory information. So I think this suggestion

> My ideal usage for the wiki would be to link every page on the README after a brief introduction to the topic and a short example.

is a good idea. It ties the most important wiki content to the README. So I agree that this would be a good approach.

I only came across the project a few weeks ago while searching for documentation issues, so I am not sure where to start beyond the list above. But if there are other important help wanted issues, I'd be happy to look into them.

**Comment by BuonOmo** [comment]
> I only came across the project a few weeks ago while searching for documentation issues, so I am not sure where to start beyond the list above. But if there are other important help wanted issues, I'd be happy to look into them.

I've tagged only one _help wanted_/_good first issue_ issue beside this one yet. @keithdoggett maybe you have more issues to add to the mix ?

Documentation is our main focus for the current month(s). Hence on documentation I think you could take one of the two next:
- how to parse various types of data: wkt, wkb, gejson, shapefile
- add examples, I think we can have an example page for the moment that list various mainstream examples. If you're not sure about one, just post it in this thread and we'll review it :)

> I was just thinking along the lines of Ruby Object Mapper, where they have sections with guides/tutorials for each of their projects in addition to their YARD generated reference docs.

Generating documentation with yard is very powerful indeed. However I still think we should start with GH pages and see what we have. I've integrated yard in some private projects, and there is a great `--markup markdown` option that will allow us to just copy paste our wiki sections (or part of sections) where it seems correct once they are written :)

I definitely agree with you that wiki can be dangerous if contributors/maintainers do not take care of updating them along with new PR. And if they are not well referenced. I think that simple solutions for both those issues are:
- referencing wiki in the README for the occasional reader / user. And maybe point rubygem directly to the wiki ?
- adding a `CONTRIBUTING` file (which we should do anyway) and PR template (idem) which both reference documentation and ask current contributor tu update or even create doc related to its changes if applicable.

**Comment by keithdoggett** [comment]
I can take a look at open issues and tag some, but I agree @BuonOmo our priority is documentation right now. Here's the existing YARD docs for reference https://rubydoc.info/gems/rgeo.

> Documentation is our main focus for the current month(s). Hence on documentation I think you could take one of the two next:
>
>    - how to parse various types of data: wkt, wkb, gejson, shapefile
>    - add examples, I think we can have an example page for the moment that list various mainstream examples. If you're not sure about one, just post it in this thread and we'll review it :)

I agree with this. Since you said you started using the package a few weeks ago, @tstewart-writer, these should be good topics to start with. I'd also tentatively add "which factory should I choose?", but that could be complex and depends on your familiarity with spatial applications in general.

Here are some articles from the creator of the package that could be helpful https://daniel-azuma.com/articles/georails.

>I definitely agree with you that wiki can be dangerous if contributors/maintainers do not take care of updating them along with new PR. And if they are not well referenced. I think that a simple first solution for both those issues are:
>
>    - referencing wiki in the README for the occasional reader / user. And maybe point rubygem directly to the wiki ?
>    - adding a CONTRIBUTING file (which we should do anyway) and PR template (idem) which both reference documentation and ask current contributor tu update or even create doc related to its changes if applicable.
 
Agreed, the best way to stay ahead of this is to make it part of the process.

**Comment by tstewart-writer** [comment]
@BuonOmo Sorry for the delay, been pretty busy with some other things lately. I was already interested in the "how to parse various types of data: wkt, wkb, gejson, shapefile" item, so I would be happy to look into it and write a guide.

@keithdoggett I'm not super familiar with spatial applications. I've written a few small spatial applications over the years, but nothing serious and nothing as a professional. So that might be biting off more than I can chew. That said, I don't mind diving into a topic. The parsing guide is probably a better option for now.
Also, thanks for the link to the GeoRails series of articles. I'll go through them. Figuring out how to replace the obsolete code might be instructive.

**Comment by dazuma** [comment]
If someone ends up doing the legwork to determine the updates needed for code in the GeoRails articles, feel free to send me the edits, and I'm happy to incorporate them into the articles and republish.

As for documentation, I tend to advocate writing markdown documents in the repo itself (preferably that are part of the YARD build and so get incorporated into the gem reference docs on rubydoc.info). It makes it easier to version the documentation and associate it with specific releases of the libraries. The problem with wikis is that they're not connected to actual library releases, so it's difficult to keep them up to date—or even to tell whether or not they are up to date.

**Comment by keithdoggett** [comment]
@tstewart-writer that sounds like a good idea to start with parsing, but if you feel inclined to try working on "choosing a factory" that would be great. If you have any questions about how something should work or want us to review something along the way let us know! We should be posting more docs soon, so some of those could be helpful to look at too.

@dazuma that's a good point about versioning and building with the RubyDocs, we hadn't considered that. Sounds like having markdown files in the repo is the best way forward and it's [easy enough](https://github.com/lsegal/yard/blob/main/docs/GettingStarted.md#documenting-extra-files) to bundle the extra files. I'll discuss more with @BuonOmo about this after the holidays.

@tstewart-writer for now feel free to put whatever file you create in the wiki or as an md file in the repo, just note where it exists. Once we hit the first documentation milestone we'll organize everything into whatever format we decide to follow and standardize from there. Thanks for your help!

**Comment by BuonOmo** [comment]
@keithdoggett @tstewart-writer FYI, I've started [a draft about _which factory should i use_](https://github.com/rgeo/rgeo/wiki/Which-factory-should-I-use%3F-(draft)). Feel free to change it by any mean ! And a happy new year 🥳

**Comment by keithdoggett** [comment]
Just want to give an update here. I made a draft of the [factory compatibility](https://github.com/rgeo/rgeo/wiki/Factory-Compatibility-(draft)) doc and made edits to the [which factory should I use?](https://github.com/rgeo/rgeo/wiki/Which-factory-should-I-use%3F-(draft)) doc. If we think those look good, I can take them out of the "draft" stage.

@BuonOmo is also working on a workflow that will take articles from the wiki and bundle them with the repo every time we do a release. It will also re-generate the compatibility table.

In the meantime, I can start making some examples. I also want to expand the README a little bit to show a few examples and give a little more information.

I also think it could be helpful to add some docs about some more general topics like projected coordinate systems, data formats, information on GEOS, and information about spatial predicates. Not sure we need all of those, but they could be helpful if a user is unfamiliar with spatial applications. We could at least point them in the right direction.

**Comment by BuonOmo** [comment]
We've done most of the work :tada:

I'm closing this issue, since @keithdoggett should send a PR soon with Examples. For the reader who still want to contribute on documentation, here are some leads on potential next steps

- Edit individual READMEs of various RGeo projects to make sure they contain examples
- Ask for a new documentation topic if there is something that is not clear in your opinion, or even better: write it once you've made the research! We'll be glad to help if you open a pull request
- Add a documentation on parsing data from various sources (wkt/wkb/geojson/shapefile/...) and basic usage for the result.
- Design a new logo and pull request it to https://github.com/rgeo/rgeo.github.io!
- Improve https://rgeo.info's design

Thanks for the work done here 😄
